spring.application.name=SinhVien5T

app.auth.frontendUrl=http://localhost:3000

# DBS
spring.datasource.url=jdbc:mysql://localhost:3306/sv5t?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=caigiday123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jackson.time-zone=UTC

# JWT
app.jwt.secret=MITbHAU2Ncg6MDEyMzO18ta4OTAxMjBATA3ODkwITM=nfwkw99454treg4ref
app.jwt.access-expiration=3600000
app.jwt.refresh-expiration=7200000

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vietbbachh@gmail.com
spring.mail.password=tetgabmgyacsyjnb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
